### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Wulfheart** [Wulfheart/dnw-next#11]
- [x] Message Authorization
- [x] Inject proper power_id
- [x] Display amount of unread messages in Gamenav
- [x] Display hint of unread message in Overview
- [x] Order submission hint
- [x] Microsoft Clarity
